
#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_noaug --ray_name ptb_resnettr_kfold_noaug --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold --ray_name ptb_resnettr_kfold --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220917-161345-ptb_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20220917-161345-ptb_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_all --ray_name ptb_resnettr_kfold_all --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100

CUDA_VISIBLE_DEVICES=1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220922-085750-ptb_resnet_kfold_cdiff-AdaAugcadaclassdiff/ --h_model_path search/ptbxl/20220922-085750-ptb_resnet_kfold_cdiff-AdaAugcadaclassdiff/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_cdiff --ray_name ptb_resnettr_kfold_cdiff --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

CUDA_VISIBLE_DEVICES=1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220922-101937-ptb_resnet_kfold_cbal-AdaAugcadaclassbal/ --h_model_path search/ptbxl/20220922-101937-ptb_resnet_kfold_cbal-AdaAugcadaclassbal/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_cbal --ray_name ptb_resnettr_kfold_cbal --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

#tmp lstm
#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptb_lstm_kfold --gpu 0.5 --cpu 2 --ray_name ptb_lstm_kfold --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup diagnostic --valselect --search_round 4

#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptb_lstm_kfold_all --gpu 0.5 --cpu 2 --ray_name ptb_lstm_kfold_all --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup diagnostic --valselect --same_train --diff_aug --loss_type relative --class_adapt --class_embed --keep_aug --keep_len 100 --search_round 4

