
#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220928-005657-ptbsub_resnet_kfold_keepbound-AdaAugkeepauto1/ --h_model_path search/ptbxl/20220928-005657-ptbsub_resnet_kfold_keepbound-AdaAugkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_keepbound05 --ray_name ptbsub_resnettr_kfold_keepbound05 --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --keep_bound 0.5

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220928-022036-ptbsub_resnet_kfold_keepgrid-AdaAugkeepauto124/ --h_model_path search/ptbxl/20220928-022036-ptbsub_resnet_kfold_keepgrid-AdaAugkeepauto124/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_keepboundgrid --ray_name ptbsub_resnettr_kfold_keepboundgrid --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --keep_seg 1 2 4 --keep_grid --keep_bound 0.25

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_creg --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_creg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --lambda_noaug 0.005

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220926-235929-ptbsub_resnet_kfold_cadd-AdaAugcadacadd/ --h_model_path search/ptbxl/20220926-235929-ptbsub_resnet_kfold_cadd-AdaAugcadacadd/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cadaadd --ray_name ptbsub_resnettr_kfold_cadaadd --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --noaug_reg cadd

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220927-104455-ptbsub_resnet_kfold_creg-AdaAugcada/ --h_model_path search/ptbxl/20220927-104455-ptbsub_resnet_kfold_creg-AdaAugcada/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cadareg --ray_name ptbsub_resnettr_kfold_cadareg --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220927-012355-ptbsub_resnet_kfold_diffnorew-AdaAugdiff2relative/ --h_model_path search/ptbxl/20220927-012355-ptbsub_resnet_kfold_diffnorew-AdaAugdiff2relative/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_dif --ray_name ptbsub_resnettr_kfold_dif --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220927-022429-ptbsub_resnet_kfold_diffsimrew-AdaAugdiff2relativerew/ --h_model_path search/ptbxl/20220927-022429-ptbsub_resnet_kfold_diffsimrew-AdaAugdiff2relativerew/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_difdsrew --ray_name ptbsub_resnettr_kfold_difdsrew --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220927-210626-ptbsub_resnet_kfold_creg-AdaAugcada/ --h_model_path search/ptbxl/20220927-210626-ptbsub_resnet_kfold_creg-AdaAugcada/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cbalreg --ray_name ptbsub_resnettr_kfold_cbalreg --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220928-031612-ptbsub_resnet_kfold_cbaladd-AdaAugcadacadd/ --h_model_path search/ptbxl/20220928-031612-ptbsub_resnet_kfold_cbaladd-AdaAugcadacadd/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cbalcadd --ray_name ptbsub_resnettr_kfold_cbalcadd --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --noaug_reg cadd

CUDA_VISIBLE_DEVICES=1,2,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220929-092804-ptbsub_resnet_kfold_keepcada-AdaAugcadakeepauto1/ --h_model_path search/ptbxl/20220929-092804-ptbsub_resnet_kfold_keepcada-AdaAugcadakeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_kcada --ray_name ptbsub_resnettr_kfold_kcada --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100

CUDA_VISIBLE_DEVICES=1,2,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220929-104914-ptbsub_resnet_kfold_cdiffadd-AdaAugcadaclassdiffcadd/ --h_model_path search/ptbxl/20220929-104914-ptbsub_resnet_kfold_cdiffadd-AdaAugcadaclassdiffcadd/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cdiffadd --ray_name ptbsub_resnettr_kfold_cdiffadd --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --noaug_reg cadd

### search ###

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_creg --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_creg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --lambda_noaug 0.05

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cbaladd --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cbaladd --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --noaug_reg cadd --search_sampler weight

#CUDA_VISIBLE_DEVICES=1,2,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_keepcada --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_keepcada --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cdiffadd --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cdiffadd --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --noaug_reg cadd --policy_loss classdiff


