
#CUDA_VISIBLE_DEVICES=4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cadd --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cadd --kfold 9 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --noaug_reg add

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cadd --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cadd --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --noaug_reg cadd

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cbalreg --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cbalreg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --lambda_noaug 0.05 --search_sampler weight

#CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_pwarm --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_pwarm --kfold 9 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --pwarmup 5

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_diffnorew --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_diffnorew --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --same_train --diff_aug --loss_type relative --not_reweight

#CUDA_VISIBLE_DEVICES=4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_simrew --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_simrew --kfold 9 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --same_train --sim_rew

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_diffsimrew --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_simrew --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --same_train --diff_aug --loss_type relative --sim_rew

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_keepbound --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_keepbound --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_bound 0.5

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_keepcada --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_keepcada --kfold 9 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_keepgrid --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_keepgrid --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_seg 1 2 4 --keep_grid --keep_bound 0.25

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cbaladd --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cbaladd --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --noaug_reg cadd --search_sampler weight

#CUDA_VISIBLE_DEVICES=1,2,4,5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220927-210626-ptbsub_resnet_kfold_creg-AdaAugcada/ --h_model_path search/ptbxl/20220927-210626-ptbsub_resnet_kfold_creg-AdaAugcada/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cadareg05 --ray_name ptbsub_resnettr_kfold_cadareg05 --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cdrop --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cdrop --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --feature_mask dropout

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cada --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cada --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --output_visual

#tmp train lambda
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221012-191008-ptbsub_resnet_kfold_cada-AdaAug/ --h_model_path search/ptbxl/20221012-191008-ptbsub_resnet_kfold_cada-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold --ray_name ptbsub_resnettr_kfold --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect
#tmp train tsadd keepauto
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221006-110428-ptbsub_resnet_kfold-AdaAugecgtsadddiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221006-110428-ptbsub_resnet_kfold-AdaAugecgtsadddiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all --ray_name ptbsub_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --augselect ecgtsadd --keep_aug --keep_len 100 --class_adapt --class_embed
#
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cmask --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cmask --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --feature_mask select

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cdconf --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cdconf --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --class_dist conf --lambda_dist 10

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cwass --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cwass --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --class_dist wass --lambda_dist 10

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cdconf --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cdconf --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --class_dist conf --lambda_dist 5

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cwass --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cwass --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --class_dist wass --lambda_dist 5

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 2 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cdmask --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cdmask --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --class_dist wass --feature_mask select --lambda_dist 10

#train
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221013-111723-ptbsub_resnet_kfold_cdconf-AdaAugcada/ --h_model_path search/ptbxl/20221013-111723-ptbsub_resnet_kfold_cdconf-AdaAugcada/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cdconf --ray_name ptbsub_resnettr_kfold_cdconf --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221013-114902-ptbsub_resnet_kfold_cwass-AdaAugcada/ --h_model_path search/ptbxl/20221013-114902-ptbsub_resnet_kfold_cwass-AdaAugcada/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cdwass --ray_name ptbsub_resnettr_kfold_cdwass --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

### valid as search
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_valsea --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_valsea --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0 --valid_search --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --keep_aug --keep_len 100 

### grid params
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbest --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbest --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00003 --search_freq 5 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 8 --class_adapt --class_embed --keep_aug --keep_len 100
#train
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221112-153644-ptbsub_resnet_kfold_allbest-AdaAugcadakeepauto1/ --h_model_path search/ptbxl/20221112-153644-ptbsub_resnet_kfold_allbest-AdaAugcadakeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allbest --ray_name ptbsub_resnettr_kfold_allbest --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

### adapt retest
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_adapt --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_adapt --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_mode adapt --keep_aug --keep_len 50 100 200 --thres_adapt --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#train
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221112-165427-ptbsub_resnet_kfold_adapt-AdaAugdiff2relativecadarewkeepadapt1/ --h_model_path search/ptbxl/20221112-165427-ptbsub_resnet_kfold_adapt-AdaAugdiff2relativecadarewkeepadapt1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_adapt --ray_name ptbsub_resnettr_kfold_adapt --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_mode adapt --keep_aug --keep_len 100 --thres_adapt

#class depend method
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_clasonly --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_classonly --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --feature_mask class_only --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_clasonly --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_classonly --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --feature_mask average --n_proj_layer 1 --n_proj_hidden 32 --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5


### class noaug method
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_creg --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_creg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --noaug_reg creg --lambda_noaug 0.03  --output_source allsearch --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cwreg --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cwreg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --noaug_reg cwreg --lambda_noaug 0.03 --output_source allsearch --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cpwreg --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cpwreg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --noaug_reg cpwreg --lambda_noaug 0.03 --output_source allsearch --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_creg --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_creg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --noaug_reg creg --lambda_noaug 0.03  --output_source allsearch --keep_aug --keep_len 100 --thres_adapt --same_train --diff_aug --loss_type relative --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cwreg --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_cwreg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --noaug_reg cwreg --lambda_noaug 0.03 --output_source allsearch --keep_aug --keep_len 100 --thres_adapt --same_train --diff_aug --loss_type relative --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=0,1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cpwreg --gpu 1 --cpu 2  --ray_name ptbsub_resnet_kfold_cpwreg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --noaug_reg cpwreg --lambda_noaug 0.03 --output_source allsearch --keep_aug --keep_len 100 --thres_adapt --same_train --diff_aug --loss_type relative --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=0,1,2,3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptb_resnet_kfold_cpwreg --gpu 0.5 --cpu 2  --ray_name ptb_resnet_kfold_cpwreg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup diagnostic --valselect --search_round 16 --class_adapt --class_embed --noaug_reg cpwreg --lambda_noaug 0.03 --output_source allsearch --keep_aug --keep_len 100 --thres_adapt --same_train --diff_aug --loss_type relative --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=0,1,2,3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptb_resnet_kfold_cpwreg --gpu 0.5 --cpu 2  --ray_name ptb_resnet_kfold_cpwreg --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup diagnostic --valselect --search_round 16 --class_adapt --class_embed --noaug_reg cpwreg --lambda_noaug 0.03 --output_source allsearch --keep_aug --keep_len 100 --thres_adapt --same_train --diff_aug --loss_type relative --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --feature_mask average --n_proj_layer 1 --n_proj_hidden 32

#train with problem
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221118-172050-ptbsub_resnet_kfold_cpwreg-AdaAugdiff2relativecadacpwregrewkeepauto1/ --h_model_path search/ptbxl/20221118-172050-ptbsub_resnet_kfold_cpwreg-AdaAugdiff2relativecadacpwregrewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cavgpwreg --ray_name ptbsub_resnettr_kfold_cavgpwreg --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100 --feature_mask average --n_proj_layer 1 --n_proj_hidden 32

#train
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221118-112836-ptbsub_resnet_kfold_cpwreg-AdaAugdiff2relativecadacpwregrewkeepauto1/ --h_model_path search/ptbxl/20221118-112836-ptbsub_resnet_kfold_cpwreg-AdaAugdiff2relativecadacpwregrewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cpwreg --ray_name ptbsub_resnettr_kfold_cpwreg --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100

#train diag
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221119-152454-ptb_resnet_kfold_cpwreg-AdaAugdiff2relativecadacpwregrewkeepauto1/ --h_model_path search/ptbxl/20221119-152454-ptb_resnet_kfold_cpwreg-AdaAugdiff2relativecadacpwregrewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_cavgpwreg --ray_name ptb_resnettr_kfold_cavgpwreg --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100 --feature_mask average --n_proj_layer 1 --n_proj_hidden 32

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221119-132309-ptb_resnet_kfold_cpwreg-AdaAugdiff2relativecadacpwregrewkeepauto1/ --h_model_path search/ptbxl/20221119-132309-ptb_resnet_kfold_cpwreg-AdaAugdiff2relativecadacpwregrewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_cpwreg --ray_name ptb_resnettr_kfold_cpwreg --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100

### class distance part
CUDA_VISIBLE_DEVICES=4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptb_resnet_kfold_cwass --gpu 1 --cpu 2  --ray_name ptb_resnet_kfold_cwass --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup diagnostic --valselect --search_round 16 --class_adapt --class_embed --class_dist wass --lambda_dist 0.5 --output_source allsearch --keep_aug --keep_len 100 --thres_adapt --same_train --diff_aug --loss_type relative --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

CUDA_VISIBLE_DEVICES=4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 0 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cwass --gpu 1 --cpu 2  --ray_name ptbsub_resnet_kfold_cwass --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --class_adapt --class_embed --class_dist wass --lambda_dist 0.5 --output_source allsearch --keep_aug --keep_len 100 --thres_adapt --same_train --diff_aug --loss_type relative --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5


