
### subdiag rerun
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-092519-ptbsub_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20220913-092519-ptbsub_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all --ray_name ptbsub_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221012-191008-ptbsub_resnet_kfold_cada-AdaAug/ --h_model_path search/ptbxl/20221012-191008-ptbsub_resnet_kfold_cada-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold --ray_name ptbsub_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221012-191008-ptbsub_resnet_kfold_cada-AdaAug/ --h_model_path search/ptbxl/20221012-191008-ptbsub_resnet_kfold_cada-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold --ray_name ptbsub_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

CUDA_VISIBLE_DEVICES=5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-092519-ptbsub_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20220913-092519-ptbsub_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all --ray_name ptbsub_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221108-100041-ptbsub_resnettr_kfold_all-AdaAugcadakeepauto1 --class_adapt --class_embed --keep_aug --keep_len 100

CUDA_VISIBLE_DEVICES=5,6 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_ball --ray_name ptbsub_resnettr_kfold_ball --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221017-061217-ptbsub_resnettr_kfold_allbal-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100

###super rerun
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220817-164935-ptbsup_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220817-164935-ptbsup_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup superdiagnostic --save ptbsup_resnettr_kfold --ray_name ptbsup_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220817-164935-ptbsup_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220817-164935-ptbsup_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup superdiagnostic --save ptbsup_resnettr_kfold --ray_name ptbsup_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220817-164935-ptbsup_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220817-164935-ptbsup_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup superdiagnostic --save ptbsup_resnettr_kfold --ray_name ptbsup_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221109-123713-ptbsup_resnettr_kfold-AdaAug/ --output_pred --output_visual
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220817-164935-ptbsup_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220817-164935-ptbsup_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup superdiagnostic --save ptbsup_resnettr_kfold --ray_name ptbsup_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221109-135425-ptbsup_resnettr_kfold-NOAUG/ --output_pred
#CUDA_VISIBLE_DEVICES=7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220903-153743-ptbsup_resnet_kfold_all2-AdaAugdiff2relativecadarewkeepauto/ --h_model_path search/ptbxl/20220903-153743-ptbsup_resnet_kfold_all2-AdaAugdiff2relativecadarewkeepauto/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup superdiagnostic --save ptbsup_resnettr_kfold_all --ray_name ptbsup_resnettr_kfold_all --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20220903-212250-ptbsup_resnet_tr_kfold_all2-AdaAugcada/ --output_pred --class_adapt --class_embed --output_visual --keep_aug --keep_len 100
#CUDA_VISIBLE_DEVICES=7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221025-170555-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221025-170555-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup superdiagnostic --save ptbsup_resnettr_kfold_ball --ray_name ptbsup_resnettr_kfold_ball --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221025-225754-ptbsup_resnettr_kfold_allbal-AdaAugcadakeepauto1/ --output_pred --output_visual --class_adapt --class_embed --keep_aug --keep_len 100
### diag rerun
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold --ray_name ptb_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold --ray_name ptb_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221109-201421-ptb_resnettr_kfold-AdaAug/ --output_pred
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold --ray_name ptb_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20220917-142718-ptb_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold --ray_name ptb_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221109-214514-ptb_resnettr_kfold-NOAUG/ --output_pred
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220917-161345-ptb_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20220917-161345-ptb_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold --ray_name ptb_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20220917-234805-ptb_resnettr_kfold_all-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221025-193317-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221025-193317-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_ball --ray_name ptb_resnettr_kfold_ball --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221026-002122-ptb_resnettr_kfold_allbal-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100
### rhythm rerun
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-080811-ptbrhythm_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221004-080811-ptbrhythm_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup rhythm --save ptbrhy_resnettr_kfold --ray_name ptbrhy_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-080811-ptbrhythm_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221004-080811-ptbrhythm_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup rhythm --save ptbrhy_resnettr_kfold --ray_name ptbrhy_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-080811-ptbrhythm_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221004-080811-ptbrhythm_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup rhythm --save ptbrhy_resnettr_kfold --ray_name ptbrhy_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221109-232729-ptbrhy_resnettr_kfold-AdaAug/ --output_pred
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-080811-ptbrhythm_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221004-080811-ptbrhythm_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup rhythm --save ptbrhy_resnettr_kfold --ray_name ptbrhy_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221110-011957-ptbrhy_resnettr_kfold-NOAUG/ --output_pred
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-210007-ptbrhythm_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221004-210007-ptbrhythm_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup rhythm --save ptbrhy_resnettr_kfold_all --ray_name ptbrhy_resnettr_kfold_all --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221005-012813-ptbrhythm_resnettr_kfold_all-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221024-043222-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221024-043222-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup rhythm --save ptbrhy_resnettr_kfold_ball --ray_name ptbrhy_resnettr_kfold_ball --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221024-200748-ptbrhy_resnettr_kfold_allbal-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100

### form rerun
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-090152-ptbform_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221004-090152-ptbform_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup form --save ptbform_resnettr_kfold --ray_name ptbform_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-090152-ptbform_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221004-090152-ptbform_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup form --save ptbform_resnettr_kfold --ray_name ptbform_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-090152-ptbform_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221004-090152-ptbform_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup form --save ptbform_resnettr_kfold --ray_name ptbform_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221110-022920-ptbform_resnettr_kfold-AdaAug/ --output_pred
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-090152-ptbform_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221004-090152-ptbform_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup form --save ptbform_resnettr_kfold --ray_name ptbform_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221110-031511-ptbform_resnettr_kfold-NOAUG/ --output_pred
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-224821-ptbform_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221004-224821-ptbform_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup form --save ptbform_resnettr_kfold --ray_name ptbform_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221005-030433-ptbform_resnettr_kfold_all-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221104-002119-ptbform_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221104-002119-ptbform_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup form --save ptbform_resnettr_kfold_ball --ray_name ptbform_resnettr_kfold_ball --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --restore --restore_path search/ptbxl/20221105-055742-ptbform_resnettr_kfold_all-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100

## chapman
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset chapman --gf_model_path search/chapman/20221014-114152-chapyuall_resnet_kfold-AdaAug/ --h_model_path search/chapman/20221014-114152-chapyuall_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset chapman  --model_name resnet_wang --labelgroup yuall --save chapyall_resnettr_kfold --ray_name chapyall_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset chapman --gf_model_path search/chapman/20221014-114152-chapyuall_resnet_kfold-AdaAug/ --h_model_path search/chapman/20221014-114152-chapyuall_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset chapman  --model_name resnet_wang --labelgroup yuall --save chapyall_resnettr_kfold --ray_name chapyall_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --kfold 10 --valselect
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset chapman --gf_model_path search/chapman/20221014-114152-chapyuall_resnet_kfold-AdaAug/ --h_model_path search/chapman/20221014-114152-chapyuall_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset chapman  --model_name resnet_wang --labelgroup yuall --save chapyall_resnettr_kfold --ray_name chapyall_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --kfold 10 --valselect --restore --restore_path search/chapman/20221110-045842-chapyall_resnettr_kfold-NOAUG/ --output_pred
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset chapman --gf_model_path search/chapman/20221014-114152-chapyuall_resnet_kfold-AdaAug/ --h_model_path search/chapman/20221014-114152-chapyuall_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset chapman  --model_name resnet_wang --labelgroup yuall --save chapyall_resnettr_kfold --ray_name chapyall_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --kfold 10 --valselect --restore --restore_path search/chapman/20221110-034235-chapyall_resnettr_kfold-AdaAug/ --output_pred
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset chapman --gf_model_path search/chapman/20221014-122711-chapyuall_resnet_kfold_all2-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/chapman/20221014-122711-chapyuall_resnet_kfold_all2-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset chapman  --model_name resnet_wang --labelgroup yuall --save chapyall_resnettr_kfold --ray_name chapyall_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --kfold 10 --valselect --restore --restore_path search/chapman/20221014-153706-chapyuall_resnettr_kfold_all-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset chapman --gf_model_path search/chapman/20221024-100344-chapyuall_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/chapman/20221024-100344-chapyuall_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset chapman  --model_name resnet_wang --labelgroup yuall --save chapyall_resnettr_kfold_ball --ray_name chapyall_resnettr_kfold_ball --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --kfold 10 --valselect --restore --restore_path search/chapman/20221024-220020-chapyuall_resnettr_kfold_allbal-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100


## icbeb ###11/10 find bug###
#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset icbeb --gf_model_path search/icbeb/20221010-153234-icbeball_resnet_kfold-AdaAug/ --h_model_path search/icbeb/20221010-153234-icbeball_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset icbeb --model_name resnet_wang --labelgroup all --save icbeball_resnettr_kfold --ray_name icbeball_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ICBEB-dataset/ --kfold 10 --valselect --restore --restore_path search/icbeb/20221110-100604-icbeball_resnettr_kfold-AdaAug/ --output_pred

#CUDA_VISIBLE_DEVICES=0,1,2,3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset icbeb --gf_model_path search/icbeb/20221010-153234-icbeball_resnet_kfold-AdaAug/ --h_model_path search/icbeb/20221010-153234-icbeball_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset icbeb --model_name resnet_wang --labelgroup all --save icbeball_resnettr_kfold --ray_name icbeball_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ICBEB-dataset/ --kfold 10 --valselect --restore --restore_path search/icbeb/20221110-112504-icbeball_resnettr_kfold-NOAUG/ --output_pred

#CUDA_VISIBLE_DEVICES=3 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset icbeb --gf_model_path search/icbeb/20221010-181645-icbeball_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/icbeb/20221010-181645-icbeball_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 0 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset icbeb --model_name resnet_wang --labelgroup all --save icbeball_resnettr_kfold --ray_name icbeball_resnettr_kfold --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ICBEB-dataset/ --kfold 10 --valselect --restore --restore_path search/icbeb/20221010-212134-icbeball_resnettr_kfold_all-AdaAugcadakeepauto1/ --output_pred --class_adapt --class_embed --keep_aug --keep_len 100




