### for randaug exp
#train sample
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221028-103550-ptbsub_lstm_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221028-103550-ptbsub_lstm_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.003 --dataset ptbxl  --model_name lstm_ptb --labelgroup subdiagnostic --save ptbsub_lstmtr_kfold_all50 --ray_name ptbsub_lstmtr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed
#search sample
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 200 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#ranaug+keep
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all --ray_name ptbsub_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --randaug --grad_clip 1 --notwarmup

#lstm with resnet policy need rerun
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1 --dataset ptbxl  --model_name lstm_ptb --labelgroup subdiagnostic --save ptbsub_lstmtr_kfold_all --ray_name ptbsub_lstmtr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221025-193317-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221025-193317-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip --dataset ptbxl  --model_name lstm_ptb --labelgroup diagnostic --save ptb_lstmtr_kfold_all --ray_name ptb_lstmtr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221025-170555-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221025-170555-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1 --dataset ptbxl  --model_name lstm_ptb --labelgroup superdiagnostic --save ptbsup_lstmtr_kfold_all --ray_name ptbsup_lstmtr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed

#result with no delta or different temperature
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all --ray_name ptbsub_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed --delta 0

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221025-193317-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221025-193317-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_all --ray_name ptb_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed --delta 0

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 1 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all --ray_name ptbsub_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed

#test search+train temp=3
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --sear_temp 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221029-194647-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221029-194647-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all --ray_name ptbsub_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed

#diag alpha=1 case
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptb_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptb_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --sear_temp 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup diagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 1
#train
CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221030-013339-ptb_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221030-013339-ptb_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_balall --ray_name ptb_resnettr_kfold_balall --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed
##important randaug+keep
CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name lstm_ptb --labelgroup subdiagnostic --save ptbsub_lstmtr_kfold_all --ray_name ptbsub_lstmtr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --randaug --grad_clip 1 --notwarmup

#keep adapt fix len, lower bal why???
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --sear_temp 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --keep_mode adapt --thres_adapt --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#minusdiff
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --sear_temp 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type minusdiff --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#fix train for rhythm, same overall better bal
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221004-210007-ptbrhythm_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221004-210007-ptbrhythm_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup rhythm --save ptbrhy_resnettr_kfold_all --ray_name ptbrhy_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --keep_back fix --class_adapt --class_embed
#keep prob skip
#leads group
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allch2bal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allch2bal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_mode auto --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 12 6 4 2 --adapt_target ch --lead_sel group
#train
CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221030-140454-ptbsub_resnet_kfold_allch2bal-AdaAugdiff2relativecadarewkeepauto1ch12642/ --h_model_path search/ptbxl/20221030-140454-ptbsub_resnet_kfold_allch2bal-AdaAugdiff2relativecadarewkeepauto1ch12642/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_balch2all --ray_name ptbsub_resnettr_kfold_balch2all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_lead 12 6 4 2 --adapt_target ch --lead_sel group --class_adapt --class_embed
#fea, train not good
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allfeabal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allfeabal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_mode auto --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 12 6 4 2 --adapt_target fea --lead_sel group

## temp all=1 case, search
CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 1 --sear_temp 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#leads correlation
CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --sear_temp 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed --augselect lead --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

## relative sample-wise
CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --sear_temp 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relativesample --policy_loss sample --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5


