
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --augselect ecg_noise --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --augselect ecg_noise --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_kcadabal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_kcadabal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --augselect ecg_noise --keep_aug --keep_len 100 --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel

#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --augselect ecg_noise

#ecg train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221018-104056-ptbsub_resnet_kfold-AdaAugecg_noise/ --h_model_path search/ptbxl/20221018-104056-ptbsub_resnet_kfold-AdaAugecg_noise/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold --ray_name ptbsub_resnettr_kfold --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --augselect ecg_noise

#tmp train retrain bal sampler case
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allbal --ray_name ptbsub_resnettr_kfold_allbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --train_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221015-120247-ptbsub_resnet_kfold_kcadabal-AdaAugcadakeepauto1/ --h_model_path search/ptbxl/20221015-120247-ptbsub_resnet_kfold_kcadabal-AdaAugcadakeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_ckeepbal --ray_name ptbsub_resnettr_kfold_ckeepbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --train_sampler wmaxrel

#tmp
#CUDA_VISIBLE_DEVICES=1,2,3,4,5 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221017-023228-ptbsub_resnet_kfold_cklenbal-AdaAugcadakeepadapt1/ --h_model_path search/ptbxl/20221017-023228-ptbsub_resnet_kfold_cklenbal-AdaAugcadakeepadapt1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allbal --ray_name ptbsub_resnettr_kfold_allbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode adapt --keep_len 50 100 200 --adapt_target len --class_adapt --class_embed

#creg
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --lambda_noaug 0.01
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221019-194654-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221019-194654-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allbalreg --ray_name ptbsub_resnettr_kfold_allbalreg --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --noaug_reg cadd --lambda_noaug 0.05
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221020-010455-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadacaddrewkeepauto1/ --h_model_path search/ptbxl/20221020-010455-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadacaddrewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allcaddbal --ray_name ptbsub_resnettr_kfold_allcaddbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --noaug_reg cadd
#only cadd
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allcaddbal --ray_name ptbsub_resnettr_kfold_allcaddbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --noaug_reg cadd
#teach reweight
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_alltrewbal --ray_name ptbsub_resnettr_kfold_alltrewbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --teach_rew
#keep bound 0.25
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221016-140345-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allbdbal --ray_name ptbsub_resnettr_kfold_allbdbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --keep_bound 0.25 --class_adapt --class_embed
#reverse keep aug, rerun
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allrevbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allrevbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --adapt_target recut --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#diff only mag
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221019-021723-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativediffcadarewkeepauto1/ --h_model_path search/ptbxl/20221019-021723-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativediffcadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_alldifwbal --ray_name ptbsub_resnettr_kfold_alldifwbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed

#1/4 data
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub025_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub025_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.75 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub025_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub025_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.75 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub025_resnet_kfold --gpu 0.5 --cpu 2  --ray_name ptbsub025_resnet_kfold --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.75 --labelgroup subdiagnostic --valselect --search_round 4
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221020-063055-ptbsub025_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221020-063055-ptbsub025_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub025_resnettr_kfold --ray_name ptbsub025_resnettr_kfold --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --search_size 0.75 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221020-063055-ptbsub025_resnet_kfold-AdaAug/ --h_model_path search/ptbxl/20221020-063055-ptbsub025_resnet_kfold-AdaAug/ --gf_model_name resnet_wang --k_ops 0 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub025_resnettr_kfold_noaug --ray_name ptbsub025_resnettr_kfold_noaug --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --search_size 0.75 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221020-044735-ptbsub025_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221020-044735-ptbsub025_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub025_resnettr_kfold_all --ray_name ptbsub025_resnettr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --search_size 0.75 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221020-052232-ptbsub025_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221020-052232-ptbsub025_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub025_resnettr_kfold_balall --ray_name ptbsub025_resnettr_kfold_balall --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --search_size 0.75 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed

#selective
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allrevcdrop --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbalcdrop --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed --feature_mask dropout --n_proj_layer 1 --n_proj_hidden 64 --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbalcsel --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allcselbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed --feature_mask select --n_proj_layer 1 --n_proj_hidden 64 --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221020-065032-ptbsub_resnet_kfold_allrevcdrop-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221020-065032-ptbsub_resnet_kfold_allrevcdrop-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_alldropbal --ray_name ptbsub_resnettr_kfold_alldropbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --feature_mask dropout --n_proj_layer 1 --n_proj_hidden 64

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221020-092518-ptbsub_resnet_kfold_allbalcsel-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221020-092518-ptbsub_resnet_kfold_allbalcsel-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allselbal --ray_name ptbsub_resnettr_kfold_allselbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --feature_mask select --n_proj_layer 1 --n_proj_hidden 64

#subset train (all,balall)
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allsubbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allsubbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed --mix_method sub
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allsubbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allsubbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --mix_method sub
#policy warmup
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allsubbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allsubbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --pwarmup 4

#keep bound search, tmp not run
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allboundbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allboundbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_bound 0.25
#creg
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allregbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allregbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --lambda_noaug 0.01
#creg train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221022-001749-ptbsub_resnet_kfold_allregbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221022-001749-ptbsub_resnet_kfold_allregbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allreg --ray_name ptbsub_resnettr_kfold_allreg --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed
#lead 2,4,6; 4 only lead
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allleadbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allleadbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 4

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allleadbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allleadbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 12 6 4 2
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221022-071333-ptbsub_resnet_kfold_allleadbal-AdaAugdiff2relativecadarewkeepauto1ch12642/ --h_model_path search/ptbxl/20221022-071333-ptbsub_resnet_kfold_allleadbal-AdaAugdiff2relativecadarewkeepauto1ch12642/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_alllead --ray_name ptbsub_resnettr_kfold_alllead --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --keep_lead 12 6 4 2
#rerun lead keep, !!!bug need fix!!!
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allleadbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allleadbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 6 4 2 --adapt_target ch

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allleadbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allleadbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_mode adapt --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 6 4 2 --adapt_target ch

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allsubbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allsubbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --pwarmup 2 --mix_method sub
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221023-003329-ptbsub_resnet_kfold_allsubbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221023-003329-ptbsub_resnet_kfold_allsubbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allsub --ray_name ptbsub_resnettr_kfold_allsub --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed

#cadd
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allcaddbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allcaddbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --noaug_reg cadd
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221023-031637-ptbsub_resnet_kfold_allcaddbal-AdaAugdiff2relativecadacaddrewkeepauto1/ --h_model_path search/ptbxl/20221023-031637-ptbsub_resnet_kfold_allcaddbal-AdaAugdiff2relativecadacaddrewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allcadd --ray_name ptbsub_resnettr_kfold_allcadd --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --noaug_reg cadd

#policy optim
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_alloptbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_alloptbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --policy_optim rmsprop
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221022-110544-ptbsub_resnet_kfold_alloptbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221022-110544-ptbsub_resnet_kfold_alloptbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allrms --ray_name ptbsub_resnettr_kfold_allrms --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed

###other dataset
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbrhy_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbrhy_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup rhythm --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbrhy_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsup_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221025-170555-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221025-170555-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup superdiagnostic --save ptbsup_resnettr_kfold_allbal --ray_name ptbsup_resnettr_kfold_allbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbrhy_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptb_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup diagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221025-193317-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221025-193317-ptbrhy_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup diagnostic --save ptb_resnettr_kfold_allbal --ray_name ptb_resnettr_kfold_allbal --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset chapman --model_name resnet_wang --save chapyuall_resnet_kfold_allbal --gpu 1 --cpu 2  --ray_name chapyuall_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --train_portion 0.5 --search_size 0.5 --labelgroup yuall --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset chapman --gf_model_path search/chapman/20221024-100344-chapyuall_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/chapman/20221024-100344-chapyuall_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset chapman  --model_name resnet_wang --labelgroup yuall --save chapyuall_resnettr_kfold_allbal --ray_name chapyuall_resnettr_kfold_allbal --gpu 1 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset icbeb --model_name resnet_wang --save icbeb_resnet_kfold_allbal --gpu 1 --cpu 2  --ray_name icbeb_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ICBEB-dataset/ --train_portion 0.5 --search_size 0.5 --labelgroup all --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

###good transfrom: test sub,chap
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_gdallbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_gdallbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --augselect goodtrans
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_gd --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_gd --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --augselect goodtrans
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221026-111849-ptbsub_resnet_kfold_gdallbal-AdaAugdiff2relativecadarewkeepauto1goodtrans/ --h_model_path search/ptbxl/20221026-111849-ptbsub_resnet_kfold_gdallbal-AdaAugdiff2relativecadarewkeepauto1goodtrans/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allgd --ray_name ptbsub_resnettr_kfold_allgd --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --class_adapt --class_embed --augselect goodtrans
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221026-211139-ptbsub_resnet_kfold_gd-AdaAuggoodtrans/ --h_model_path search/ptbxl/20221026-211139-ptbsub_resnet_kfold_gd-AdaAuggoodtrans/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_gd --ray_name ptbsub_resnettr_kfold_gd --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --augselect goodtrans

#chap
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset chapman --model_name resnet_wang --save chapyall_resnet_kfold_gdallbal --gpu 1 --cpu 2  --ray_name chapyall_resnet_kfold_gdallbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --train_portion 0.5 --search_size 0.5 --labelgroup yuall --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --augselect goodtrans
#with submix diffw
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset chapman --model_name resnet_wang --save chapyall_resnet_kfold_gdallbal --gpu 1 --cpu 2  --ray_name chapyall_resnet_kfold_gdallbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --train_portion 0.5 --search_size 0.5 --labelgroup yuall --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relativediff --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --augselect goodtrans --mix_method sub
#train


###keep len quick
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 50 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 200 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

###channel keep train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221023-095214-ptbsub_resnet_kfold_allleadbal-AdaAugdiff2relativecadarewkeepauto1ch642/ --h_model_path search/ptbxl/20221023-095214-ptbsub_resnet_kfold_allleadbal-AdaAugdiff2relativecadarewkeepauto1ch642/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_alllead --ray_name ptbsub_resnettr_kfold_alllead --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --adapt_target ch --class_adapt --class_embed --keep_lead 6 4 2
# BUG
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allch2bal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allch2bal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_mode auto --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 12 6 4 2 --adapt_target ch
#keep fea auto
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allfeabal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allfeabal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_mode auto --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 12 6 4 2 --adapt_target fea
#tr
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221027-133838-ptbsub_resnet_kfold_allfeabal-AdaAugdiff2relativecadarewkeepauto1ch12642/ --h_model_path search/ptbxl/20221027-133838-ptbsub_resnet_kfold_allfeabal-AdaAugdiff2relativecadarewkeepauto1ch12642/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allfea --ray_name ptbsub_resnettr_kfold_allfea --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 --adapt_target fea --class_adapt --class_embed --keep_lead 12 6 4 2
### channel keep adapt
#bad perfrom
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allladabal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allladabal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_mode adapt --keep_len 500 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_lead 12 6 4 2 --adapt_target ch --mix_method ind
#keep fea adapt
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allfadabal --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allfadabal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_mode adapt --keep_len 50 100 200 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --adapt_target fea --mix_method ind
#tr need rerun
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221027-192048-ptbsub_resnet_kfold_allfadabal-AdaAugdiff2relativecadarewkeepadapt1/ --h_model_path search/ptbxl/20221027-192048-ptbsub_resnet_kfold_allfadabal-AdaAugdiff2relativecadarewkeepadapt1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_allfada --ray_name ptbsub_resnettr_kfold_allfada --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode adapt --keep_len 50 100 200 --adapt_target fea --class_adapt --class_embed
#len 50 train need rerun
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221026-015433-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221026-015433-ptbsub_resnet_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all50 --ray_name ptbsub_resnettr_kfold_all50 --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 50 --class_adapt --class_embed
#minusdiff need rerun
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allmdif --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allmdif --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type minusdiff --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#keep prob need rerun
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_allkprob --gpu 0.5 --cpu 2  --ray_name ptbsub_resnet_kfold_allkprob --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5 --keep_prob 0.5
#current best lstm version
#CUDA_VISIBLE_DEVICES=0,1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1 --dataset ptbxl --model_name lstm_ptb --save ptbsub_lstm_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsub_lstm_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#train
#CUDA_VISIBLE_DEVICES=3,4,5,6,7 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221028-103550-ptbsub_lstm_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221028-103550-ptbsub_lstm_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1 --dataset ptbxl  --model_name lstm_ptb --labelgroup subdiagnostic --save ptbsub_lstmtr_kfold_all50 --ray_name ptbsub_lstmtr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed
##waiting
#CUDA_VISIBLE_DEVICES=0,1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 3 --dataset ptbxl --model_name lstm_ptb --save ptbsup_lstm_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptbsup_lstm_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5

CUDA_VISIBLE_DEVICES=0,1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 3 --dataset ptbxl --model_name lstm_ptb --save ptb_lstm_kfold_allbal --gpu 0.5 --cpu 2  --ray_name ptb_lstm_kfold_allbal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.00005 --search_freq 10 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup diagnostic --valselect --search_round 16 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed  --train_sampler wmaxrel --search_sampler wmaxrel --alpha 0.5
#train
CUDA_VISIBLE_DEVICES=0,1,2 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20221030-002551-ptbsub_lstm_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20221030-002551-ptbsub_lstm_kfold_allbal-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 1 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1 --dataset ptbxl  --model_name lstm_ptb --labelgroup subdiagnostic --save ptbsub_lstmtr_kfold_all --ray_name ptbsub_lstmtr_kfold_all --gpu 0.5 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_mode auto --keep_len 100 --class_adapt --class_embed



