
#CUDA_VISIBLE_DEVICES=5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptbsup_lstm_kfold --gpu 0.33 --cpu 2  --ray_name ptbsup_lstm_kfold --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 4

#CUDA_VISIBLE_DEVICES=5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptbsup_lstm_kfold_dif --gpu 0.33 --cpu 2  --ray_name ptbsup_lstm_kfold_dif --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 4 --diff_aug --loss_type relative --same_train

#CUDA_VISIBLE_DEVICES=5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptbsup_lstm_kfold_ori --gpu 0.33 --cpu 2  --ray_name ptbsup_lstm_kfold_ori --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.001 --search_freq 3 --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --search_round 4

#CUDA_VISIBLE_DEVICES=5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptbsup_lstm_kfold_cada --gpu 0.33 --cpu 2  --ray_name ptbsup_lstm_kfold_cada --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 4 --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptbsup_lstm_kfold_cdiff --gpu 0.33 --cpu 2  --ray_name ptbsup_lstm_kfold_cdiff --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 4 --diff_aug --loss_type relative --same_train --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=0,5,6 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptbsup_lstm_kfold_all --gpu 0.5 --cpu 2  --ray_name ptbsup_lstm_kfold_all --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 4 --diff_aug --loss_type relative --same_train --class_adapt --class_embed --keep_aug --keep_len 100

CUDA_VISIBLE_DEVICES=0 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl --model_name lstm_ptb --save ptbsup_lstm_kfold_all --gpu 1 --cpu 4 --ray_name ptbsup_lstm_kfold_all --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 4 --diff_aug --loss_type relative --same_train --class_adapt --class_embed --keep_aug --keep_len 100 200 400 --keep_mode adapt


