
#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220912-163325-ptbsup_lstm_kfold_dif-AdaAugdiff2relativerew/ --h_model_path search/ptbxl/20220912-163325-ptbsup_lstm_kfold_dif-AdaAugdiff2relativerew/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl  --model_name lstm_ptb --labelgroup superdiagnostic --save ptbsup_resnettr_kfold_diff --ray_name ptbsup_lstmtr_kfold_diff --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220912-132305-ptbsup_lstm_kfold-AdaAug/ --h_model_path search/ptbxl/20220912-132305-ptbsup_lstm_kfold-AdaAug/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl  --model_name lstm_ptb --labelgroup superdiagnostic --save ptbsup_resnettr_kfold --ray_name ptbsup_lstmtr_kfold --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220912-214801-ptbsup_lstm_kfold_ori-AdaAug/ --h_model_path search/ptbxl/20220912-214801-ptbsup_lstm_kfold_ori-AdaAug/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl  --model_name lstm_ptb --labelgroup superdiagnostic --save ptbsup_lstmtr_kfold_ori --ray_name ptbsup_lstmtr_kfold_ori --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-015924-ptbsup_lstm_kfold_cada-AdaAugcada/ --h_model_path search/ptbxl/20220913-015924-ptbsup_lstm_kfold_cada-AdaAugcada/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl  --model_name lstm_ptb --labelgroup superdiagnostic --save ptbsup_lstmtr_kfold_cada --ray_name ptbsup_lstmtr_kfold_cada --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-043934-ptbsup_lstm_kfold_cdiff-AdaAugdiff2relativecadarew/ --h_model_path search/ptbxl/20220913-043934-ptbsup_lstm_kfold_cdiff-AdaAugdiff2relativecadarew/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl  --model_name lstm_ptb --labelgroup superdiagnostic --save ptbsup_lstmtr_kfold_cdif --ray_name ptbsup_lstmtr_kfold_cdif --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-075929-ptbsup_lstm_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20220913-075929-ptbsup_lstm_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name lstm_ptb --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.003 --grad_clip 1.0 --dataset ptbxl  --model_name lstm_ptb --labelgroup superdiagnostic --save ptbsup_lstmtr_kfold_all --ray_name ptbsup_lstmtr_kfold_all --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100

#tmp

#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset chapman --model_name resnet_wang --save chapmanr_resnet_kfold --gpu 0.33 --cpu 2  --ray_name chapmanr_resnet_kfold --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --train_portion 0.5 --search_size 0.5 --labelgroup rhythm --valselect --search_round 4

#CUDA_VISIBLE_DEVICES=3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset chapman --model_name resnet_wang --save chapmanr_resnet_kfold_all --gpu 0.33 --cpu 2  --ray_name chapmanr_resnet_kfold_all --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/CWDA_research/CWDA/datasets/WFDB_ChapmanShaoxing/ --train_portion 0.5 --search_size 0.5 --labelgroup rhythm --valselect --search_round 4 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed


