
#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_kada --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_kada --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 200 400 --keep_mode adapt

#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_dif --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_dif --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --same_train --diff_aug --loss_type relative

#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_keep --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_keep --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 --keep_mode auto

#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cada --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_cada --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 100 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsup_resnet_kfold_dif --gpu 0.33 --cpu 2  --ray_name ptbsup_resnet_kfold_dif --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup superdiagnostic --valselect --search_round 4 --same_train --diff_aug --loss_type relative

CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_kada2 --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_kada2 --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 200 400 --keep_mode adapt

CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_kadadif --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_kadadif --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 200 400 --keep_mode adapt --same_train --diff_aug --loss_type relative

CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cadabal --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_cadabal --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --policy_loss classbal 

CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_cadadif --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_cadadif --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --class_adapt --class_embed --policy_loss classdiff

CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_all --gpu 0.33 --cpu 2  --ray_name ptbsub_resnet_kfold_all --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 --same_train --diff_aug --loss_type relative --class_adapt --class_embed


