
#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220910-000911-ptbsub_resnet_kfold_kada-AdaAugkeepadapt1/ --h_model_path search/ptbxl/20220910-000911-ptbsub_resnet_kfold_kada-AdaAugkeepadapt1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_kada --ray_name ptbsub_resnettr_kfold_kada --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 200 400 --keep_mode adapt

#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220910-014932-ptbsub_resnet_kfold_dif-AdaAugdiff2relativerew/ --h_model_path search/ptbxl/20220910-014932-ptbsub_resnet_kfold_dif-AdaAugdiff2relativerew/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_dif --ray_name ptbsub_resnettr_kfold_dif --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect

#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220910-025220-ptbsub_resnet_kfold_keep-AdaAugkeepauto1/ --h_model_path search/ptbxl/20220910-025220-ptbsub_resnet_kfold_keep-AdaAugkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_keep --ray_name ptbsub_resnettr_kfold_keep --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100

#CUDA_VISIBLE_DEVICES=1,2,3,4 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220910-035029-ptbsub_resnet_kfold_cada-AdaAugcada/ --h_model_path search/ptbxl/20220910-035029-ptbsub_resnet_kfold_cada-AdaAugcada/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cada --ray_name ptbsub_resnettr_kfold_cada --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

#tmprun
CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_search_ts.py --k_ops 1 --report_freq 5 --num_workers 4 --epochs 50 --batch_size 128  --learning_rate 0.01  --dataset ptbxl --model_name resnet_wang --save ptbsub_resnet_kfold_kada2 --gpu 0.5 --cpu 4  --ray_name ptbsub_resnet_kfold_kada2 --kfold 10 --weight_decay 0.01 --proj_learning_rate 0.0001 --search_freq 10  --temperature 3 --dataroot /mnt/data2/teddy/ptbxl-dataset --train_portion 0.5 --search_size 0.5 --labelgroup subdiagnostic --valselect --search_round 4 --keep_aug --keep_len 100 200 400 --keep_mode adapt --class_adapt --class_embed --same_train --diff_aug --loss_type relative

#CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-204601-ptbsub_resnet_kfold_kada2-AdaAugkeepadapt1/ --h_model_path search/ptbxl/20220913-204601-ptbsub_resnet_kfold_kada2-AdaAugkeepadapt1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_kada --ray_name ptbsub_resnettr_kfold_kada --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 200 400 --keep_mode adapt

#CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-003230-ptbsub_resnet_kfold_kadadif-AdaAugdiff2relativerewkeepadapt1/ --h_model_path search/ptbxl/20220913-003230-ptbsub_resnet_kfold_kadadif-AdaAugdiff2relativerewkeepadapt1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_kadadif --ray_name ptbsub_resnettr_kfold_kadadif --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --keep_aug --keep_len 100 200 400 --keep_mode adapt

#CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-063738-ptbsub_resnet_kfold_cadabal-AdaAugcadaclassbal/ --h_model_path search/ptbxl/20220913-063738-ptbsub_resnet_kfold_cadabal-AdaAugcadaclassbal/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cbal --ray_name ptbsub_resnettr_kfold_cbal --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-075936-ptbsub_resnet_kfold_cadadif-AdaAugcadaclassdiff/ --h_model_path search/ptbxl/20220913-075936-ptbsub_resnet_kfold_cadadif-AdaAugcadaclassdiff/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_cdif --ray_name ptbsub_resnettr_kfold_cdif --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed

#CUDA_VISIBLE_DEVICES=1,2 python ada_aug/fold_train_ts.py --temperature 3 --delta 0.3 --search_dataset ptbxl --gf_model_path search/ptbxl/20220913-092519-ptbsub_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --h_model_path search/ptbxl/20220913-092519-ptbsub_resnet_kfold_all-AdaAugdiff2relativecadarewkeepauto1/ --gf_model_name resnet_wang --k_ops 1 --report_freq 10 --num_workers 2 --epochs 50 --batch_size 128 --learning_rate 0.01 --dataset ptbxl  --model_name resnet_wang --labelgroup subdiagnostic --save ptbsub_resnettr_kfold_all --ray_name ptbsub_resnettr_kfold_all --gpu 0.33 --cpu 2 --weight_decay 0.01 --train_portion 1 --dataroot /mnt/data2/teddy/ptbxl-dataset --kfold 10 --valselect --class_adapt --class_embed --keep_aug --keep_len 100


